version: "3.9"

services:
  db:
    image: postgres:16
    container_name: studentloans-db
    restart: always
    environment:
      POSTGRES_USER: studentuser
      POSTGRES_PASSWORD: studentpass
      POSTGRES_DB: studentloans
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: studentloans-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: studentloans-frontend
    restart: always
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
